# Generated by Django 4.2.11 on 2024-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling_business',
            name='business_details',
        ),
        migrations.RemoveField(
            model_name='selling_business',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='service_business',
            name='business_details',
        ),
        migrations.RemoveField(
            model_name='service_business',
            name='customer',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.TextField(default='all', max_length=25),
        ),
        migrations.AddField(
            model_name='business',
            name='delivery_options',
            field=models.BooleanField(default=True),
        ),
    ]
