# Generated by Django 4.2.11 on 2024-04-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prods_servs', '0002_alter_product_seller_delete_service'),
        ('businesses', '0002_remove_selling_business_business_details_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selling_Business',
        ),
        migrations.DeleteModel(
            name='Service_Business',
        ),
    ]
