# Generated by Django 4.2.11 on 2024-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_delete_selling_business_delete_service_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='city',
            new_name='location',
        ),
        migrations.AddField(
            model_name='business',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='banner',
            field=models.CharField(default='https://i.pinimg.com/564x/34/c3/2d/34c32d93468f7527488a188efa30c7e1.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='delivery_options',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.CharField(default='https://i.pinimg.com/originals/92/06/23/92062396ec80ec776743d10db0938789.gif', max_length=255),
        ),
    ]
