# Generated by Django 4.2.11 on 2024-04-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('images', models.ManyToManyField(to='prods_servs.image')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='businesses.service_business')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('units', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('images', models.ManyToManyField(to='prods_servs.image')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.selling_business')),
            ],
        ),
    ]
