# Generated by Django 4.2.11 on 2024-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prods_servs', '0002_alter_product_seller_delete_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='des',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.TextField(default='all', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='all', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
