# Generated by Django 4.2.11 on 2024-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
